In [20]:
from datasets import load_dataset

imdb_train = load_dataset("stanfordnlp/imdb")

print(imdb_train)
print(type(imdb_train ))

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})
<class 'datasets.dataset_dict.DatasetDict'>

### What is Hugging Face?

Hugging Face is an AI company that develops tools and resources for building applications using machine learning. It's particularly known for its open-source libraries like `Transformers`, which provides state-of-the-art models for Natural Language Processing (NLP), and `Datasets`, which offers a vast collection of ready-to-use datasets and tools for efficient data loading and processing.

### Loading Datasets with `load_dataset`

The `datasets` library from Hugging Face provides the `load_dataset` function, which is a powerful and convenient way to fetch and prepare datasets for machine learning tasks. It can load datasets from various sources, including:

-   **Hugging Face Hub**: Thousands of publicly available datasets.
-   **Local files**: CSV, JSON, Parquet, text files, etc.
-   **Custom scripts**: Define your own loading logic for complex data formats.

When `load_dataset` is called without specifying a `split`, it often returns a `DatasetDict` object, which acts like a dictionary containing different splits (e.g., 'train', 'test', 'validation') of the dataset.

Accessing train data

In [21]:
imdb_train_split = imdb_train['train']
imdb_train_split

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

### Understanding the `Dataset` Object

A `Dataset` object is a core data structure in the Hugging Face `datasets` library. It's similar to a Pandas DataFrame but optimized for large datasets and machine learning workflows. Key features include:

-   **Efficiency**: Uses Apache Arrow for memory efficiency and fast operations.
-   **Features**: It has a `features` attribute that describes the columns (fields) and their data types, which can include nested structures or custom types.
-   **Metadata**: Stores metadata about the dataset.
-   **Map/Filter**: Provides methods for easily transforming and filtering data in parallel.

In [22]:
imdb_train

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

removing unsupervised data

In [23]:
imdb_train_train_test = imdb_train.pop('unsupervised')
print(imdb_train_train_test)

Dataset({
    features: ['text', 'label'],
    num_rows: 50000
})

In [24]:
imdb_train

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
})

If we want to download only a particular split of the data from the hub.

In [25]:
only_train = load_dataset("stanfordnlp/imdb", split= 'train')
only_train

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

### Loading Specific Data Splits

When using `load_dataset`, you can specify a particular `split` to load only a subset of the data directly from the Hugging Face Hub or a local source. This is useful when you only need, for example, the training portion of a dataset and want to avoid loading the entire dataset into memory or creating unnecessary splits.

Now, if we want to split this train dataset into train & test(Validation set) set.

In [26]:
trainTest = only_train.train_test_split(test_size=0.2)
trainTest

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 20000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 5000
    })
})

### Splitting a Dataset with `train_test_split`

The `Dataset` object comes with a convenient `train_test_split` method that allows you to divide an existing `Dataset` into new training and testing (or validation) subsets. You can specify:

-   `test_size`: The proportion of the dataset to include in the test split (e.g., `0.2` for 20%).
-   `train_size`: The proportion for the training split (if not specified, it's `1 - test_size`).
-   `shuffle`: Whether to shuffle the data before splitting (default is `True`).
-   `seed`: For reproducibility, to ensure the split is the same every time.

if you have`local_dataset`

In [27]:
import pandas as pd

d1 = pd.read_csv('train.csv')
d2 = pd.read_csv('test.csv')

print((d1.shape))
print((d2.shape))

(891, 12)
(418, 11)

In [28]:
d1.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
628,629,0,3,"Bostandyeff, Mr. Guentcho",male,26.0,0,0,349224,7.8958,NaN,S

In [29]:
d2['Survived'] = d1.iloc[:419, 1]

In [30]:
d2.sample()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.0,1,0,11778,55.4417,C116,C,0

In [31]:
print((d1.info()))
print((d2.info()))

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    str
 3   Sex          418 non-null    str
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    str
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     str
 10  Embarked     418 non-null    str
 11  Survived     418 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 56.1 KB
None

Since both train.csv & train.csv have different number of features.

In [32]:
data_files = {'train': 'train.csv', 'test': 'test.csv'}

local_dataset = load_dataset('csv', data_files=data_files)

local_dataset

DatasetDict({
    train: Dataset({
        features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
        num_rows: 891
    })
    test: Dataset({
        features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
        num_rows: 418
    })
})

In [33]:
local_dataset.save_to_disk('pyarrow_dataset/titanic')

Saving the dataset (1/1 shards): 100%|██████████| 891/891 [00:00<00:00, 67218.10 examples/s]
Saving the dataset (1/1 shards): 100%|██████████| 418/418 [00:00<00:00, 100736.56 examples/s]

loading back from the `pyarrow_dataset` directory usning `load_from_disk` function

In [34]:
from datasets import load_from_disk

load_ds = load_from_disk('pyarrow_dataset/titanic')

In [35]:
load_ds

DatasetDict({
    train: Dataset({
        features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
        num_rows: 891
    })
    test: Dataset({
        features: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
        num_rows: 418
    })
})

### Saving and Loading Datasets Locally

The `datasets` library allows you to save your processed `DatasetDict` or `Dataset` objects to disk and load them back efficiently. This is particularly useful for:

-   **Persistence**: Saving preprocessing work so you don't have to re-run it.
-   **Sharing**: Easily share processed datasets with others without sharing the raw data and code.
-   **Offline use**: Work with datasets without an internet connection.

-   **`save_to_disk()`**: This method stores the dataset (or `DatasetDict`) in a specified local directory, typically using Apache Arrow or Parquet format, which is optimized for fast I/O.
-   **`load_from_disk()`**: This function is used to load a dataset or `DatasetDict` that was previously saved using `save_to_disk()` from a local path.

### `save_to_disk()` and Apache Arrow/Parquet Format

Yes, the `save_to_disk()` method in the Hugging Face `datasets` library primarily saves data in formats optimized for efficient I/O, such as **Apache Arrow** or **Parquet**. These formats are columnar, which means they store data column by column rather than row by row. This design is highly beneficial for analytical workloads and machine learning as it allows for:

-   **Faster reads**: Only necessary columns need to be read from disk.
-   **Better compression**: Similar data types within a column can be compressed more effectively.
-   **Memory efficiency**: Data can be memory-mapped, reducing the need to load entire datasets into RAM.

By leveraging these formats, `save_to_disk()` ensures that datasets can be quickly stored and reloaded, preserving their structure and types, and maintaining performance for large-scale data operations.